spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: ADMIN-SERVICE
#          uri: lb://ADMIN-SERVICE
#          predicates:
#            - Path=/admin/**
#        - id: REVIEW-SERVICE
#          uri: lb://REVIEW-SERVICE
#          predicates:
#            - Path=/review/**

server:
  port: 9191

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
