info:
  app:
    name: ${SPRING_APPLICATION_NAME}
    description: "FYP Grading project - API Gateway"
    version: ${BUILD_VERSION}

logging:
  level:
    root: INFO

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false # do not locate services and default routes from eureka, only explicitly coded routes
          lower-case-service-id: true
#  data:
#    redis:
#      host: localhost
#      port: 6379

#resilience4j:
#  circuitbreaker:
#    instances:
#      adminServiceCircuitBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: COUNT_BASED
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 5
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        event-consumer-buffer-size: 10
#      adminServieAuthenticationCircuitBreaker:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        permittedNumberOfCallsInHalfOpenState: 3
#        slidingWindowType: TIME_BASED
#
#  timelimiter:
#    instances:
#      adminServiceCircuitBreaker:
#        timeoutDuration: 2s
#        cancelRunningFuture: true
#      adminServieAuthenticationCircuitBreaker:
#        timeoutDuration: 1s
#        cancelRunningFuture: false

server:
  port: ${PORT}
