spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379

ribbon:
  eureka:
    enabled: true

server:
  port: 9191

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      adminServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 5s
        failureRateThreshold: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        event-consumer-buffer-size: 10
      adminServieAuthenticationCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED

  timelimiter:
    instances:
      adminServiceCircuitBreaker:
        timeoutDuration: 2s
        cancelRunningFuture: true
      adminServieAuthenticationCircuitBreaker:
        timeoutDuration: 1s
        cancelRunningFuture: false

app:
  services:
    address:
      admin: http://localhost
      evaluation: http://localhost
      rubrics: http://localhost
      notification: http://localhost